Catalog.create("name"=>"Test Catalog Name")
Category.create("catalogs_id"=>1, "name"=>"Men")
Category.create("catalogs_id"=>1, "name"=>"Women")
Category.create("catalogs_id"=>1, "name"=>"Children")
Product.create("categories_id"=>1, "name"=>"Men Shirts Dress Khaki", "sku"=>"EW239", "price"=>"46.99", "short_description"=>"The description for Men Shirt Dress Khaki", "image"=>"mens_shirts_dresscas_Dkhaki.gif")
Product.create("categories_id"=>1, "name"=>"Men Pants Dress", "sku"=>"FD320", "price"=>"45.99", "short_description"=>"The description for Men Pants Dress", "image"=>"mens_pants_dress.gif")
Product.create("categories_id"=>1, "name"=>"Men Pants Cords", "sku"=>"HG875", "price"=>"10.99", "short_description"=>"The description for Men Pants Cords", "image"=>"mens_pants_cords.gif")
Product.create("categories_id"=>1, "name"=>"Men Shirts Dress Stone", "sku"=>"CY543", "price"=>"68.99", "short_description"=>"The description for Men Shirts Dress Stone", "image"=>"mens_shirts_dress_stone.gif")
Product.create("categories_id"=>1, "name"=>"Men Shirts Dress Stone II", "sku"=>"TY332", "price"=>"67.99", "short_description"=>"The description for Men Shirts Dress Stone II", "image"=>"mens_shirts_dresscas_stone.gif")
Product.create("categories_id"=>2, "name"=>"Women Sleepwear", "sku"=>"BC198", "price"=>"21.99", "short_description"=>"The description for Women Sleepwear", "image"=>"womens_sleepwear_short_Iblue.gif")
Product.create("categories_id"=>2, "name"=>"Women Dress", "sku"=>"AY723", "price"=>"78.99", "short_description"=>"The description for Women Dress", "image"=>"womens_dress_pink_Db.gif")
Product.create("categories_id"=>2, "name"=>"Women Activewear Soccer", "sku"=>"PO193", "price"=>"23.99", "short_description"=>"The description for Women Activewear Soccer", "image"=>"womens_activewear_soccer_Ob.gif")
Product.create("categories_id"=>2, "name"=>"Women Activewear 1Piece", "sku"=>"CV389", "price"=>"32.99", "short_description"=>"The description for Women Activewear 1Piece", "image"=>"womens_activewear_1piece_in.gif")
Product.create("categories_id"=>2, "name"=>"Women Accessories Handbag", "sku"=>"SBC163", "price"=>"15.99", "short_description"=>"The description for Women Accessories Handbag", "image"=>"womens_accessories_handbag.gif")
Product.create("categories_id"=>2, "name"=>"Women Accessories Belt Nav", "sku"=>"AU0023", "price"=>"11.99", "short_description"=>"The description for Women Accessories Belt Nav", "image"=>"womens_accessories_belt_nav.gif")
Product.create("categories_id"=>2, "name"=>"Women Accessories Belt Brown", "sku"=>"BC003", "price"=>"10.99", "short_description"=>"The discription for Women Accessories Belt Brown", "image"=>"womens_accessories_belt_brw.gif")
